const favorites = [
  "One of Comet's favorite sniffs is Pine trees",
  "One of Comet's favorite sniffs is Deer tracks",
  "One of Comet's favorite sniffs is Grandma's hoodie",
  "One of Comet's favorite treats is Liver",
  "One of Comet's favorite treats is Hot baloney",
  "One of Comet's favorite treats is Chicken",
  "One of Comet's favorite activities is Forest walks",
  "One of Comet's favorite activities is Rolling in stinky stuff",
  "One of Comet's favorite activities is Sleeping",
  "One of Skylark's favorite adventures is Kite flying",
  "One of Skylark's favorite adventures is Climbing trees",
  "One of Skylark's favorite adventures is Exploring trails",
  "One of Skylark's favorite books is Inspirational",
  "One of Skylark's favorite books is Historical fiction",
  "One of Skylark's favorite books is Adventures",
  "One of Skylark's favorite hobbies is Drawing",
  "One of Skylark's favorite hobbies is Bird watching",
  "One of Skylark's favorite hobbies is Writing short stories",
  "One of Willow's favorite books is About animals",
  "One of Willow's favorite books is About adventure girls",
  "One of Willow's favorite books is Comic books",
  "One of Willow's favorite hobbies is Playing dress-up",
  "One of Willow's favorite hobbies is Make-believe",
  "One of Willow's favorite hobbies is Acting out stories",
  "One of Willow's favorite things is Stuffed animals",
  "One of Willow's favorite things is Princess dresses",
  "One of Willow's favorite things is Cats",
  "One of Coach's favorite books is Inspirational",
  "One of Coach's favorite books is Educational",
  "One of Coach's favorite books is Fantasy",
  "One of Coach's favorite hobbies is Coaching",
  "One of Coach's favorite hobbies is Organizing",
  "One of Coach's favorite hobbies is Teaching",
  "One of Coach's favorite favorite sports is Volleyball",
  "One of Coach's favorite favorite sports is Soccer",
  "One of Coach's favorite favorite sports is Running",
  "One of Sport's favorite activities is Soccer",
  "One of Sport's favorite activities is Softball",
  "One of Sport's favorite activities is Swimming",
  "One of Sport's favorite hobbies is Climbing",
  "One of Sport's favorite hobbies is Going to the ocean",
  "One of Sport's favorite hobbies is Playing piano",
  "One of Sport's favorite things is Trampoline",
  "One of Sport's favorite things is Animals",
  "One of Sport's favorite things is Puzzles",
  "One of Blaze's favorite adventures is Soccer",
  "One of Blaze's favorite adventures is Climbing trees",
  "One of Blaze's favorite adventures is Going to the ocean",
  "One of Blaze's favorite books is Fantasy",
  "One of Blaze's favorite books is Historical fiction",
  "One of Blaze's favorite books is Adventure stories",
  "One of Blaze's favorite games is Switch Just Dance",
  "One of Blaze's favorite games is Mario Kart",
  "One of Blaze's favorite games is Board games",
  "One of Ranger's favorite tools is Chainsaw",
  "One of Ranger's favorite tools is Sledgehammer",
  "One of Ranger's favorite tools is ATV",
  "One of Ranger's favorite treats is Black coffee",
  "One of Ranger's favorite treats is BHK",
  "One of Ranger's favorite treats is Crazy pie",
  "One of Ranger's favorite activities is Clearing trails",
  "One of Ranger's favorite activities is Spotting wildlife",
  "One of Ranger's favorite activities is Burning brush",
  "One of Stella's favorite foods is Peanut butter biscuits",
  "One of Stella's favorite foods is Bacon",
  "One of Stella's favorite foods is Chicken",
  "One of Stella's favorite hobbies is Greeting visitors",
  "One of Stella's favorite hobbies is Sleeping",
  "One of Stella's favorite hobbies is Playing",
  "One of Stella's favorite friends is Mario",
  "One of Stella's favorite friends is Unicorn",
  "One of Stella's favorite friends is Neighborhood pups",
  "One of Rocket's favorite books is The Martian",
  "One of Rocket's favorite books is Project Hail Mary",
  "One of Rocket's favorite books is Ender's Game",
  "One of Rocket's favorite foods is Tequila Harry's / Tacos",
  "One of Rocket's favorite foods is Dad's Chili",
  "One of Rocket's favorite foods is Ice cream",
  "One of Rocket's favorite hobbies is Walking in the forest",
  "One of Rocket's favorite hobbies is Writing code",
  "One of Rocket's favorite hobbies is Adventures",
  "One of Dynamo's favorite hobbies is Pinterest",
  "One of Dynamo's favorite hobbies is Facebook",
  "One of Dynamo's favorite hobbies is Party planning",
  "One of Dynamo's favorite treats is Nice restaurants",
  "One of Dynamo's favorite treats is Getting together with friends",
  "One of Dynamo's favorite treats is All-inclusive beach resorts",
  "One of Dynamo's favorite shows is Scary movies",
  "One of Dynamo's favorite shows is Real TV",
  "One of Dynamo's favorite shows is Cops",
  "One of Unicorn's favorite things is Beautiful shoes",
  "One of Unicorn's favorite things is Pink cupcakes",
  "One of Unicorn's favorite things is Princess dresses",
  "One of Unicorn's favorite hobbies is Playing dress-up",
  "One of Unicorn's favorite hobbies is Drawing rainbows",
  "One of Unicorn's favorite hobbies is Working with pups",
  "One of Unicorn's favorite books is About animals",
  "One of Unicorn's favorite books is About adventures",
  "One of Unicorn's favorite books is About princesses",
  "One of Kernel's favorite tech is Python",
  "One of Kernel's favorite tech is Kubernetes",
  "One of Kernel's favorite tech is Chips",
  "One of Kernel's favorite hobbies is Board games",
  "One of Kernel's favorite hobbies is Cooperative games",
  "One of Kernel's favorite hobbies is Coaching",
  "One of Kernel's favorite sports is Baseball",
  "One of Kernel's favorite sports is Soccer",
  "One of Kernel's favorite sports is Hiking",
  "One of Guardian's favorite sports is Chiefs Football",
  "One of Guardian's favorite sports is Chicago Cubs Baseball",
  "One of Guardian's favorite sports is Competitive Grilling",
  "One of Guardian's favorite shows is Friends",
  "One of Guardian's favorite shows is Cops",
  "One of Guardian's favorite shows is Bluey",
  "One of Guardian's favorite treats is Italian Food",
  "One of Guardian's favorite treats is BBQ",
  "One of Guardian's favorite treats is Coffee",
  "One of Duchess's favorite locations is Sunny window ledge",
  "One of Duchess's favorite locations is Warm laundry basket",
  "One of Duchess's favorite locations is Mom and Dad's room",
  "One of Duchess's favorite hobbies is Napping",
  "One of Duchess's favorite hobbies is Managing the dog",
  "One of Duchess's favorite hobbies is Hiding out",
  "One of Duchess's favorite foods is Salmon",
  "One of Duchess's favorite foods is Catnip",
  "One of Duchess's favorite foods is Early breakfast",
  "One of Mario's favorite animals is T-Rex",
  "One of Mario's favorite animals is Shark",
  "One of Mario's favorite animals is Tiger",
  "One of Mario's favorite hobbies is Mario Kart",
  "One of Mario's favorite hobbies is Super Smash Bros",
  "One of Mario's favorite hobbies is Lego master",
  "One of Mario's favorite foods is Pizza",
  "One of Mario's favorite foods is Tacos",
  "One of Mario's favorite foods is Chocolate chip cookies"
];