name: Build All HTML Pages

on:
  push:
    paths:
      - 'peeps/*.md'
  workflow_dispatch:    # Allows manual run

permissions:
  contents: write 

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install markdown

    - name: Generate HTML from Markdown
      run: python .github/scripts/build_all_views.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add views/*.html
        git commit -m "Auto-generate HTML pages from Markdown"
        git push
