name: 4: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["3: Build Index"]
    types:
      - completed
  workflow_dispatch:    # Allows manual run

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull latest changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git pull origin main --rebase

    - name: Verify deploy directory
      run: |
        if [ ! -d "./views" ]; then
          echo "❌ Deploy directory not found. Exiting."
          exit
