name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Build Index"]
    types:
      - completed
  workflow_dispatch:    # Allows manual run

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./    # Deploy the root of main
